name: reviewdog-suggester
on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    branches: [ try_mvi ]
    paths-ignore: [ '**.md' ]

jobs:
  kotlin:
    name: runner / suggester / spotless
    runs-on: ubuntu-latest
    steps:
      - name: Check try_mvi branch
        uses: actions/checkout@v4
        with:
          ref: try_mvi

      - name: Checkout current branch
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Cache gradle, wrapper and buildSrc
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-spotless-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}
          restore-keys: |
            ${{ runner.os }}-spotless-

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Decode PLACE_API_KEY
        env:
          BASEURL: ${{ secrets.PLACE_API_KEY }}
        run: echo PLACE_API_KEY="$PLACE_API_KEY" > ./local.properties

      - name: Spotless apply
        run: ./gradlew spotlessKotlinApply

      - name: Reviewdog
        uses: reviewdog/action-suggester@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tool_name: spotless

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Spotless check
        run: ./gradlew spotlessKotlinCheck
